return {
  settings = {
    yaml = {
      schemas = {
        kubernetes = {
          -- "daemon.{yml,yaml}",
          -- "manager.{yml,yaml}",
          -- "restapi.{yml,yaml}",
          -- "role.{yml,yaml}",
          -- "role_binding.{yml,yaml}",
          "*onfigma*.{yml,yaml}",
          "*ngres*.{yml,yaml}",
          "*ecre*.{yml,yaml}",
          "*eployment*.{yml,yaml}",
          "*ervic*.{yml,yaml}",
          -- "kubectl-edit*.yaml",
        },
      },
      hover = true,
      completion = true,
      validate = { enable = true },
      customTags = {
        "!Ref",
        "!GetAtt",
        "!FindInMap sequence",
        "!FindInMap scalar",
        "!GetAtt",
        "!GetAZs",
        "!Cidr",
        "!ImportValue",
        "!Join sequence",
        "!Select",
        "!Split",
        "!Sub sequence",
        "!Sub scalar",
        "!And",
        "!Equals",
        "!If",
        "!Not",
        "!Or",
      },
    },
  },
}
